on:
  push:
    branches:
      - main

name: Building LLama.CPP-CUDA from git

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ matrix.distro }} / pkg_llama.cpp-cuda-git-${{ matrix.version }}-${{ matrix.pkgver }}

    strategy:
      fail-fast: false
      matrix:
        distro: ["arch"]
        version: ["b5338"]
        pkgver: ["1"]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: |
          docker build ${{ matrix.distro }} -t mybuild

      - name: copy
        run: |
          docker run -d --name myrun mybuild
          docker exec myrun ls -l /home/arch/pkg_llama.cpp-cuda-git/
          docker cp myrun:/home/arch/pkg_llama.cpp-cuda-git/llama.cpp-cuda-git-${{ matrix.version }}-${{ matrix.pkgver }}-x86_64.pkg.tar.zst .
          docker cp myrun:/home/arch/pkg_llama.cpp-cuda-git/llama.cpp-cuda-git.sha256sum ./llama.cpp-cuda-git-${{ matrix.version }}-${{ matrix.pkgver }}-x86_64.pkg.sha256sum
          docker stop myrun

      - name: store
        uses: actions/upload-artifact@v4
        with:
          name: llama.cpp-cuda-git-${{ matrix.version }}-${{ matrix.pkgver }}
          path: |
            llama.cpp-cuda-git-${{ matrix.version }}-${{ matrix.pkgver }}-x86_64.*

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ matrix.version }}-${{ matrix.pkgver }}
          name: Release ${{ matrix.version }}-${{ matrix.pkgver }}
          draft: false
          prerelease: false
          files: |
            llama.cpp-cuda-git-${{ matrix.version }}-${{ matrix.pkgver }}-x86_64.pkg.tar.zst
            llama.cpp-cuda-git-${{ matrix.version }}-${{ matrix.pkgver }}-x86_64.pkg.sha256sum
